name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-code:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Extract request from issue/comment
        id: extract-request
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            echo "request=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "request=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Process Claude Request
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extrahiere die Aufgabe nach @claude
          REQUEST="${{ steps.extract-request.outputs.request }}"
          CLAUDE_REQUEST=$(echo "$REQUEST" | sed -n 's/.*@claude\s*\(.*\)/\1/p')
          
          if [ -n "$CLAUDE_REQUEST" ]; then
            echo "Processing Claude request: $CLAUDE_REQUEST"
            
            # Erstelle eine einfache Antwort auf das Issue
            gh issue comment ${{ steps.extract-request.outputs.issue_number }} --body "🤖 **Claude Code Assistant aktiviert** - **Aufgabe:** $CLAUDE_REQUEST - Ich habe deine Anfrage erhalten und arbeite daran. Bitte gib mir einen Moment..."

            # Hier könntest du später die eigentliche Implementierung hinzufügen
            # Für jetzt nur eine Bestätigungsnachricht
            
            echo "Claude request processed: $CLAUDE_REQUEST"
          fi